-- =============================================================================
-- Exercício Prático: Banco de Dados - Controle de Inventário de Laboratórios
--
-- PARTE 2 - MODELO FÍSICO (DDL)
-- "Escreva o código SQL (CREATE TABLE) para criar as duas tabelas no banco."
--
-- SGBD alvo: PostgreSQL 16
-- Codificação do arquivo: UTF-8
-- Execução: psql -U <usuario> -d <banco> -f 03-modelo-fisico.sql
-- =============================================================================

-- ORDEM DE EXCLUSÃO: o inverso da criação.
-- Primeiro sai a tabela que DEPENDE (equipamentos), depois a tabela PRINCIPAL
-- (laboratorios). Tentar apagar laboratorios antes daria erro, porque ainda
-- existiria uma chave estrangeira apontando para ela.
DROP TABLE IF EXISTS equipamentos;
DROP TABLE IF EXISTS laboratorios;

-- -----------------------------------------------------------------------------
-- 1a) Tabela PRINCIPAL: laboratorios
--
-- Precisa ser criada PRIMEIRO. A tabela equipamentos vai referenciar a chave
-- primária daqui, e o SGBD só aceita uma REFERENCES para algo que já existe.
-- -----------------------------------------------------------------------------
CREATE TABLE laboratorios (
    id_laboratorio  INT          GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR(60)  NOT NULL,
    bloco           VARCHAR(30)  NOT NULL,

    -- Número de identificação único do laboratório.
    CONSTRAINT pk_laboratorios      PRIMARY KEY (id_laboratorio),
    -- Evita cadastrar o mesmo laboratório duas vezes.
    CONSTRAINT uq_laboratorios_nome UNIQUE (nome)
);

COMMENT ON TABLE  laboratorios                IS 'Salas onde os equipamentos ficam alocados.';
COMMENT ON COLUMN laboratorios.id_laboratorio IS 'Chave primária: número de identificação único.';
COMMENT ON COLUMN laboratorios.nome           IS 'Nome descritivo. Ex: Lab. de Redes.';
COMMENT ON COLUMN laboratorios.bloco          IS 'Bloco onde o laboratório está. Ex: Bloco A.';

-- -----------------------------------------------------------------------------
-- 1b) Tabela DEPENDENTE: equipamentos
--
-- Criada DEPOIS, porque contém a chave estrangeira id_laboratorio.
-- -----------------------------------------------------------------------------
CREATE TABLE equipamentos (
    id_equipamento  INT          GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR(80)  NOT NULL,
    patrimonio      VARCHAR(20)  NOT NULL,
    id_laboratorio  INT          NOT NULL,   -- NOT NULL = associação obrigatória

    -- Número de identificação único do equipamento.
    CONSTRAINT pk_equipamentos            PRIMARY KEY (id_equipamento),
    -- Número de patrimônio único em toda a instituição.
    CONSTRAINT uq_equipamentos_patrimonio UNIQUE (patrimonio),

    -- CHAVE ESTRANGEIRA: é ela que faz o relacionamento 1:N funcionar.
    -- ON UPDATE CASCADE  -> se o id do laboratório mudar, os equipamentos acompanham.
    -- ON DELETE RESTRICT -> impede apagar um laboratório que ainda tem equipamentos
    --                       (evitaria registros órfãos, proibidos pela regra de negócio).
    CONSTRAINT fk_equipamentos_laboratorio FOREIGN KEY (id_laboratorio)
        REFERENCES laboratorios (id_laboratorio)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

COMMENT ON TABLE  equipamentos                IS 'Itens de informática controlados pelo inventário.';
COMMENT ON COLUMN equipamentos.id_equipamento IS 'Chave primária: número de identificação único.';
COMMENT ON COLUMN equipamentos.nome           IS 'Nome do equipamento. Ex: Roteador Cisco.';
COMMENT ON COLUMN equipamentos.patrimonio     IS 'Número de patrimônio único. Ex: PAT-1234.';
COMMENT ON COLUMN equipamentos.id_laboratorio IS 'Chave estrangeira: laboratório onde o item está.';

-- -----------------------------------------------------------------------------
-- Índice na chave estrangeira
-- O PostgreSQL indexa PRIMARY KEY e UNIQUE automaticamente, mas não a FK.
-- Como toda consulta do inventário faz JOIN por id_laboratorio, o índice abaixo
-- evita varrer a tabela inteira de equipamentos a cada relatório.
-- -----------------------------------------------------------------------------
CREATE INDEX idx_equipamentos_laboratorio ON equipamentos (id_laboratorio);
