-- =============================================================================
-- Tarefa 1 - Modelo Conceitual, Lógico e Físico
-- Laboratório Prático: SQL DML Avançado - Especial Copa do Mundo
--
-- 1.3 MODELO FÍSICO - script DDL (Data Definition Language)
--
-- SGBD alvo: PostgreSQL 16
-- Codificação do arquivo: UTF-8
-- Execução: psql -U <usuario> -d <banco> -f 03-modelo-fisico.sql
-- =============================================================================

-- Remove os objetos na ordem inversa das dependências, para o script poder ser
-- reexecutado do zero quantas vezes for necessário.
DROP TABLE IF EXISTS jogadores;
DROP TABLE IF EXISTS clubes;
DROP TABLE IF EXISTS selecoes;

-- -----------------------------------------------------------------------------
-- Tabela: selecoes
-- País que o jogador representa na Copa do Mundo.
-- -----------------------------------------------------------------------------
CREATE TABLE selecoes (
    id_selecao  INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    pais        VARCHAR(60)  NOT NULL,
    continente  VARCHAR(20)  NOT NULL,

    CONSTRAINT pk_selecoes            PRIMARY KEY (id_selecao),
    CONSTRAINT uq_selecoes_pais       UNIQUE (pais),
    CONSTRAINT ck_selecoes_continente CHECK (
        continente IN ('América do Sul', 'América do Norte', 'Europa',
                       'África', 'Ásia', 'Oceania')
    )
);

COMMENT ON TABLE  selecoes            IS 'Seleções nacionais participantes do torneio.';
COMMENT ON COLUMN selecoes.id_selecao IS 'Chave primária, gerada automaticamente.';
COMMENT ON COLUMN selecoes.pais       IS 'País representado pela seleção (único).';
COMMENT ON COLUMN selecoes.continente IS 'Continente da confederação. Domínio fechado.';

-- -----------------------------------------------------------------------------
-- Tabela: clubes
-- Time onde o jogador atua no resto do ano.
-- -----------------------------------------------------------------------------
CREATE TABLE clubes (
    id_clube    INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    nome_clube  VARCHAR(80)  NOT NULL,
    pais_sede   VARCHAR(60)  NOT NULL,

    CONSTRAINT pk_clubes           PRIMARY KEY (id_clube),
    -- Chave candidata: não existem dois clubes de mesmo nome no mesmo país.
    CONSTRAINT uq_clubes_nome_pais UNIQUE (nome_clube, pais_sede)
);

COMMENT ON TABLE  clubes            IS 'Clubes de origem dos atletas.';
COMMENT ON COLUMN clubes.id_clube   IS 'Chave primária, gerada automaticamente.';
COMMENT ON COLUMN clubes.nome_clube IS 'Nome do clube.';
COMMENT ON COLUMN clubes.pais_sede  IS 'País onde o clube disputa o campeonato nacional.';

-- -----------------------------------------------------------------------------
-- Tabela: jogadores
-- Entidade principal: liga uma seleção a um clube (lado "N" dos dois 1:N).
-- -----------------------------------------------------------------------------
CREATE TABLE jogadores (
    id_jogador     INTEGER        GENERATED BY DEFAULT AS IDENTITY,
    nome           VARCHAR(120)   NOT NULL,
    id_selecao     INTEGER        NOT NULL,
    id_clube       INTEGER        NOT NULL,
    posicao        VARCHAR(20)    NOT NULL,
    gols_marcados  INTEGER        NOT NULL DEFAULT 0,
    -- Em milhões de euros, com 2 casas decimais: 150.00 = 150 milhões.
    valor_mercado  NUMERIC(10,2)  NOT NULL DEFAULT 0,

    CONSTRAINT pk_jogadores PRIMARY KEY (id_jogador),

    -- Integridade referencial: a seleção/clube referenciado tem de existir.
    -- RESTRICT impede apagar uma seleção ou clube que ainda tenha jogadores;
    -- CASCADE no update propaga uma eventual troca de id para os jogadores.
    CONSTRAINT fk_jogadores_selecao FOREIGN KEY (id_selecao)
        REFERENCES selecoes (id_selecao)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_jogadores_clube FOREIGN KEY (id_clube)
        REFERENCES clubes (id_clube)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    -- Domínio de posições conforme a nomenclatura das planilhas oficiais da FIFA.
    CONSTRAINT ck_jogadores_posicao CHECK (
        posicao IN ('Goleiro', 'Zagueiro', 'Lateral', 'Volante', 'Meio-Campo', 'Atacante')
    ),
    CONSTRAINT ck_jogadores_gols  CHECK (gols_marcados >= 0),
    CONSTRAINT ck_jogadores_valor CHECK (valor_mercado >= 0)
);

COMMENT ON TABLE  jogadores               IS 'Atletas do torneio. Cada um pertence a uma seleção e a um clube.';
COMMENT ON COLUMN jogadores.id_jogador    IS 'Chave primária, gerada automaticamente.';
COMMENT ON COLUMN jogadores.nome          IS 'Nome do atleta.';
COMMENT ON COLUMN jogadores.id_selecao    IS 'FK para selecoes: seleção que o atleta representa.';
COMMENT ON COLUMN jogadores.id_clube      IS 'FK para clubes: clube onde o atleta atua.';
COMMENT ON COLUMN jogadores.posicao       IS 'Posição em campo. Domínio fechado.';
COMMENT ON COLUMN jogadores.gols_marcados IS 'Gols marcados pelo atleta na competição.';
COMMENT ON COLUMN jogadores.valor_mercado IS 'Valor de mercado estimado, em MILHÕES de euros (unidade das planilhas da FIFA).';

-- -----------------------------------------------------------------------------
-- Índices
-- O PostgreSQL cria índice automaticamente para PRIMARY KEY e UNIQUE, mas não
-- para chaves estrangeiras. Como os relatórios do enunciado fazem JOIN e
-- agrupamento por seleção e por clube, os índices abaixo evitam varredura
-- completa da tabela de jogadores.
-- -----------------------------------------------------------------------------
CREATE INDEX idx_jogadores_selecao ON jogadores (id_selecao);
CREATE INDEX idx_jogadores_clube   ON jogadores (id_clube);
CREATE INDEX idx_jogadores_posicao ON jogadores (posicao);
